<?php
/**
 * Copyright © Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * See COPYING.txt for license details.
 */
?>
<?php if($crumbs && is_array($crumbs)): ?>
    <div class="breadcrumbs">
        <ul>
            <?php foreach($crumbs as $_crumbName => $_crumbInfo): ?>
                <li class="<?php echo $_crumbName ?>">
                <?php if($_crumbInfo['link']): ?>
                    <?php $href = (false !== strpos($_crumbInfo['link'], '://')) ? $_crumbInfo['link'] : Mage::getUrl($_crumbInfo['link']) ?>
                    <a href="<?php echo $href ?>" title="<?php echo $this->escapeHtml($_crumbInfo['label']) ?>"><?php echo $this->escapeHtml($this->__($_crumbInfo['label'])) ?></a>
                <?php elseif($_crumbInfo['last']): ?>
                    <?php echo $this->escapeHtml($this->__($_crumbInfo['label'])) ?>
                <?php else : ?>
                    <?php echo $this->escapeHtml($this->__($_crumbInfo['label'])) ?>
                <?php endif ?>
                <?php if(!$_crumbInfo['last']): ?>
                    <span>/ </span>
                <?php endif ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
<?php endif ?>
